### ISSUE TITLE
Curve25519 lib error

### ISSUE THREAD

**Issue by jwu-au** [SteeBono/airplayreceiver#15]
I hit below error for some reason when connecting from my mobile.
Do you have any clue? Nuget seems restore the Curve25519 lib successfully.
I ran in windows 10 using VS2022.
```
IP address fe80::2d6d:601:da5:809c%5
IP address 192.168.9.99
NIC 'Internet1'
Client connected: 192.168.9.152:53603
System.TypeLoadException: Could not load type 'org.whispersystems.curve25519.Curve25519' from assembly 'Curve25519, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null'.
   at AirPlay.Listeners.AirTunesListener.OnDataReceivedAsync(Request request, Response response, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at AirPlay.Listeners.AirTunesListener.OnDataReceivedAsync(Request request, Response response, CancellationToken cancellationToken)
   at AirPlay.Listeners.BaseTcpListener.ReadFormattedAsync(TcpClient client, NetworkStream stream, CancellationToken cancellationToken) in D:\Source\airplayreceiver\AirPlay\Listeners\Bases\BaseTcpListener.cs:line 174
   at AirPlay.Listeners.BaseTcpListener.HandleClientAsync(TcpClient client, CancellationToken cancellationToken) in D:\Source\airplayreceiver\AirPlay\Listeners\Bases\BaseTcpListener.cs:line 89
```

**Comment by SteeBono** [comment]
Can you post your proj file? Also check version of restored nuget lib.
